### ISSUE TITLE
知道是由于相对导入的路径不正确导致的 ，但不知道如何解决

### ISSUE THREAD

**Issue by TIMIXIXI** [aoguai/HumManBot#1]
from .crawler import crawl
ImportError: attempted relative import with no known parent package

**Comment by aoguai** [comment]
这个报错通常发生在使用相对导入时没有正确设置导入路径的情况下。因为在chatbot.py文件中使用了相对导入语法 from .crawler import crawl。这意味着 crawler.py 文件是在与当前文件相同的目录下的子目录中。如果 crawler.py 文件不是在这个位置，你需要相应地调整导入语句。

**Comment by TIMIXIXI** [comment]
> 这个报错通常发生在使用相对导入时没有正确设置导入路径的情况下。因为在 chatbot.py 文件中使用了相对导入语法 from .crawler import crawl。这意味着 crawler.py 文件是在与当前文件相同的目录下的子目录中。如果 crawler.py 文件不是在这个位置，你需要相应地调整导入语句。

试了多次
还是不太会 请大佬帮助

**Comment by aoguai** [comment]
> > 这个报错通常发生在使用相对导入时没有正确设置导入路径的情况下。因为在 chatbot.py 文件中使用了相对导入语法 from .crawler import crawl。这意味着 crawler.py 文件是在与当前文件相同的目录下的子目录中。如果 crawler.py 文件不是在这个位置，你需要相应地调整导入语句。
> 
> 试了多次 还是不太会 请大佬帮助

我也不知道你是什么环境，你可以多尝试，例如：
try:
    from .crawler import crawl
except ImportError:
    from crawler import crawl

**Comment by aoguai** [comment]
> > 这个报错通常发生在使用相对导入时没有正确设置导入路径的情况下。因为在 chatbot.py 文件中使用了相对导入语法 from .crawler import crawl。这意味着 crawler.py 文件是在与当前文件相同的目录下的子目录中。如果 crawler.py 文件不是在这个位置，你需要相应地调整导入语句。
> 
> 试了多次 还是不太会 请大佬帮助

我也不知道你是什么环境，你可以多尝试，例如：
```python
try:
    from .crawler import crawl
except ImportError:
    from crawler import crawl
```
